version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: drug-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/drugdb
      - JWT_SECRET=mysecretkey
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  mongo:
    image: mongo:6
    container_name: drug-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
